spring:
  redis:
    host: 192.168.100.130
    port: 6379
    password:

    database: 0 #哪数据库
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间
